# Generated by Django 4.1.5 on 2023-02-07 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bunny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField()),
                ('level', models.IntegerField()),
                ('intell', models.IntegerField()),
                ('defense', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('color', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('owner', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('active', models.BooleanField()),
            ],
        ),
    ]
