# Generated by Django 4.1.5 on 2023-02-07 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bunny',
            name='color',
            field=models.CharField(max_length=20),
        ),
    ]
