# Generated by Django 4.1.5 on 2023-02-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_bunny_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='bunny',
            name='t_days',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
