# Generated by Django 4.1.5 on 2023-02-09 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main_app", "0003_bunny_t_days"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bunny",
            name="owner",
        ),
        migrations.AddField(
            model_name="bunny",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
