# Generated by Django 4.1.5 on 2023-02-09 15:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0004_remove_bunny_owner_bunny_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="bunny",
            name="parent_1",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="bunny",
            name="parent_2",
            field=models.CharField(default="", max_length=200),
            preserve_default=False,
        ),
    ]
