# Generated by Django 4.1.5 on 2023-02-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main_app", "0005_bunny_parent_1_bunny_parent_2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bunny",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
